"""
src/llm/refinement_generation.py
----------------------------------
Interface contracts and deterministic placeholder logic for LLM-based prompt refinement.

Provides the foundational classes for generating candidate prompt mutations,
enforcing token budgets, and handling truncations without coupling to a
specific LLM provider or optimization loop logic.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List

from src.utils.token_utils import estimate_token_count

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enums and Dataclasses
# ---------------------------------------------------------------------------

class RefinementTarget(Enum):
    """Identifies the specific component being refined."""
    ROLE = "role"
    ENRICHMENT = "instruction_enrichment"
    COT = "cot"
    FEWSHOT = "few_shot"


@dataclass
class RefinementRequest:
    """
    Structured payload sent to the refinement generator.

    Attributes:
        target_component:     Which component is being targeted.
        current_content:      The existing content of the component.
        token_budget:         Maximum allowed tokens for the refined content.
        failure_summary:      Text summary of the errors/failures to fix.
        optimization_signals: Active signals (e.g. ['high_fn', 'plateau']).
        contextual_examples:  Optional failure cases or examples for context.
    """
    target_component: RefinementTarget
    current_content: str
    token_budget: int
    failure_summary: str
    optimization_signals: List[str]
    contextual_examples: List[Dict[str, str]] = field(default_factory=list)


@dataclass
class RefinementResponse:
    """
    Structured output received from the refinement generator.

    Attributes:
        refined_content: The final string to be used (truncated if necessary).
        token_count:     Token estimate of `refined_content`.
        within_budget:   Whether the LLM originally stayed within budget.
        truncated:       True if the framework had to aggressively truncate
                         the LLM output to fit the budget.
        metadata:        Additional debug/provider information.
    """
    refined_content: str
    token_count: int
    within_budget: bool
    truncated: bool
    metadata: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Base Generator Interface
# ---------------------------------------------------------------------------

class BaseRefinementGenerator(ABC):
    """
    Abstract base class for LLM refinement generation.

    Responsibilities:
    - Defines the structural contract (Request -> Response).
    - Enforces token budgets deterministically.
    - Centralizes token counting logic.
    """

    def generate_refinement(self, request: RefinementRequest) -> RefinementResponse:
        """
        Generate refined content and securely wrap it in budget constraints.

        Args:
            request: The generation instructions.

        Returns:
            A sanitized and bounded RefinementResponse.
        """
        if request.token_budget < 0:
            raise ValueError(f"Token budget cannot be negative (got {request.token_budget}).")

        # 1. Subclass handles raw generation
        raw_content = self._generate(request)

        # 2. Count tokens of the raw output
        raw_token_count = self._count_tokens(raw_content)

        # 3. Check budget adherence
        within_budget = self._is_within_budget(raw_token_count, request.token_budget)

        # 4. Truncate aggressively if violated
        final_content, was_truncated, final_count = self._enforce_budget(
            raw_content, raw_token_count, request.token_budget
        )

        return RefinementResponse(
            refined_content=final_content,
            token_count=final_count,
            within_budget=within_budget,
            truncated=was_truncated,
            metadata={
                "original_raw_tokens": raw_token_count,
                "provider": self.__class__.__name__
            }
        )

    @abstractmethod
    def _generate(self, request: RefinementRequest) -> str:
        """
        Abstract hook for actual LLM or placeholder inference.

        Args:
            request: The structural instructions.

        Returns:
            The raw string output generated by the model.
        """
        pass

    # -----------------------------------------------------------------------
    # Helper Methods
    # -----------------------------------------------------------------------

    @staticmethod
    def _count_tokens(text: str) -> int:
        """Delegate to the central token estimator."""
        return estimate_token_count(text)

    @staticmethod
    def _is_within_budget(token_count: int, budget: int) -> bool:
        """Check if the count strictly adheres to the budget."""
        return token_count <= budget

    @staticmethod
    def _enforce_budget(text: str, current_count: int, budget: int) -> tuple[str, bool, int]:
        """
        Aggressive fallback truncation if the model ignores the prompt budget.

        Returns:
            Tuple of (truncated_text, was_truncated_boolean, new_token_count).
        """
        if current_count <= budget:
            return text, False, current_count

        if budget == 0:
            return "", True, 0

        # Simple whitespace splitting for fallback truncation, aligning
        # with our `estimate_token_count` baseline strategy.
        words = text.split()
        truncated_words = words[:budget]
        truncated_text = " ".join(truncated_words)
        
        return truncated_text, True, budget


# ---------------------------------------------------------------------------
# Deterministic Placeholder Implementation
# ---------------------------------------------------------------------------

class DeterministicPlaceholderGenerator(BaseRefinementGenerator):
    """
    A strictly deterministic placeholder for testing without LLM dependencies.
    """

    def _generate(self, request: RefinementRequest) -> str:
        if not request.current_content:
            return ""
            
        # Trigger an intentional overflow for testing if a magic word is present
        if "OVERFLOW_TEST" in request.current_content:
            return "overflowing " * (request.token_budget + 5)
            
        signal_count = len(request.optimization_signals)
        return f"Refined {request.target_component.value} fixing {signal_count} signals."
